# Generated by Django 5.0.2 on 2024-06-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='instructor',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='record',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
