# Generated by Django 5.0.2 on 2024-06-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_record_instructor_record_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='record2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100)),
                ('subdomain', models.CharField(max_length=100)),
                ('coursename', models.CharField(default='Unknown', max_length=100)),
                ('instructor', models.CharField(default='Unknown', max_length=100)),
                ('video', models.CharField(max_length=1000)),
            ],
        ),
    ]
